version: '3'

services:
 php-host:
    image: vyanev/php
    ports:
    - "9000:9000"
 nginx-host:
    image: vyanev/nginx
    ports:
    - "80:80"
    links:
    - php-host
    deploy: 
      mode: replicated
      replicas: 3
 redis-host:
    image: redis:latest